football/config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
	root 'teams#index'
  resources :teams
  resources :users
  resources :team_users
    
end

football/app/models/match.rb
class Match < ApplicationRecord
	has_many :games, dependent: :restrict_with_exception

	before_create :init

private
	def init
		self.status = "In progress"
		self.winner = "Pending"
	end

end

football/app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  before_action :set_match, only: [:show, :edit, :update, :destroy]

  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.all
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
  end

  # GET /matches/new
  def new
    @match = Match.new
  end

  # POST /matches
  # POST /matches.json
  def create
    @match = Match.new

    respond_to do |format|
      if @match.save
        format.html { redirect_to @match, notice: 'Match was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # DELETE /matches/1
  # DELETE /matches/1.json
  def destroy
    @match.destroy
    respond_to do |format|
      format.html { redirect_to matches_url, notice: 'Match was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_match
      @match = Match.find(params[:id])
    end

end

football/app/helpers/matches_helper.rb
module MatchesHelper
end

football/app/views/matches/_form.html.erb
<%= form_for(match) do |f| %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

football/app/views/matches/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Matches</h1>

Match data will automatically update when we have a winning team.
<br>

<table>
  <thead>
    <tr>
      <th>Match ID</th>
      <th>Status</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @matches.each do |match| %>
      <tr>
        <td><%= match.id %></td>
        <td><%= match.status %></td>
        <td><%= match.winner %></td>
        <td><%= link_to 'Show', match %></td>
        <td><%= link_to 'Edit', edit_match_path(match) %></td>
        <td><%= link_to 'Destroy', match, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Match', new_match_path %>

football/app/views/matches/new.html.erb
<h1>New Match</h1>

<%= render 'form', match: @match %>

<%= link_to 'Back', matches_path %>

football/app/views/matches/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Status:</strong>
  <%= @match.status %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @match.winner %>
</p>

<%= link_to 'Edit', edit_match_path(@match) %> |
<%= link_to 'Back', matches_path %>