football/config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
	root 'teams#index'
  resources :teams
  resources :users
  resources :team_users
    
end

football/app/models/team_user.rb
class TeamUser < ApplicationRecord
  belongs_to :team
  belongs_to :user

  validates :user_id, :uniqueness => {:scope=>:team_id}
	validate :check_user_number

private
    def check_user_number
        if self.team.users.count >= 2
					errors.add :team, "cannot have more than 2 users"
        end
    end

end

football/app/controllers/team_users_controller.rb
class TeamUsersController < ApplicationController
  before_action :set_team_user, only: [:show, :edit, :update, :destroy]

  # GET /team_users
  # GET /team_users.json
  def index
    @team_users = TeamUser.all
  end

  # GET /team_users/1
  # GET /team_users/1.json
  def show
  end

  # GET /team_users/new
  def new
    @team_user = TeamUser.new
  end

  # GET /team_users/1/edit
  def edit
  end

  # POST /team_users
  # POST /team_users.json
  def create
    @team_user = TeamUser.new(team_user_params)

    respond_to do |format|
      if @team_user.save
        format.html { redirect_to @team_user, notice: 'Team user was successfully created.' }
        format.json { render :show, status: :created, location: @team_user }
      else
        format.html { render :new }
        format.json { render json: @team_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /team_users/1
  # PATCH/PUT /team_users/1.json
  def update
    respond_to do |format|
      if @team_user.update(team_user_params)
        format.html { redirect_to @team_user, notice: 'Team user was successfully updated.' }
        format.json { render :show, status: :ok, location: @team_user }
      else
        format.html { render :edit }
        format.json { render json: @team_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /team_users/1
  # DELETE /team_users/1.json
  def destroy
    @team_user.destroy
    respond_to do |format|
      format.html { redirect_to team_users_url, notice: 'Team user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team_user
      @team_user = TeamUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def team_user_params
      params.require(:team_user).permit(:team_id, :user_id)
    end
end

football/app/helpers/team_users_helper.rb
module TeamUsersHelper
end

football/app/views/team_users/_form.html.erb
<%= form_for(team_user) do |f| %>
  <% if team_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(team_user.errors.count, "error") %> prohibited this team_user from being saved:</h2>

      <ul>
      <% team_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.collection_select(:team_id, Team.order(:name), :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.collection_select(:user_id, User.order(:last_name), :id, :last_name) %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

football/app/views/team_users/edit.html.erb
<h1>Editing Team User</h1>

<%= render 'form', team_user: @team_user %>

<%= link_to 'Show', @team_user %> |
<%= link_to 'Back', team_users_path %>

football/app/views/team_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Team Users</h1>

<table>
  <thead>
    <tr>
      <th>Team</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @team_users.each do |team_user| %>
      <tr>
        <td><%= team_user.team.name %></td>
        <td><%= team_user.user.last_name %></td>
        <td><%= link_to 'Show', team_user %></td>
        <td><%= link_to 'Edit', edit_team_user_path(team_user) %></td>
        <td><%= link_to 'Destroy', team_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Team User', new_team_user_path %>

football/app/views/team_users/new.html.erb
<h1>New Team User</h1>

<%= render 'form', team_user: @team_user %>

<%= link_to 'Back', team_users_path %>

football/app/views/team_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @team_user.team.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @team_user.user.last_name %>
</p>

<%= link_to 'Edit', edit_team_user_path(@team_user) %> |
<%= link_to 'Back', team_users_path %>