football/config/routes.rb
Rails.application.routes.draw do
  resources :matches
  resources :games
	root 'teams#index'
  resources :teams
  resources :users
  resources :team_users
    
end

football/app/models/game.rb
class Game < ApplicationRecord
	  belongs_to :team
    belongs_to :opponent, class_name: "Team", foreign_key: "team_id"
    belongs_to :match

	validates :team_score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 11 }, presence: true
	validates :opponent_score, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than: 11 }, presence: true

	validate :not_match_self
	validate :only_three
	before_save :set_winner
	after_save :update_match

	def winner 
			if team_score > opponent_score 
					team.name
			else 
					opponent.name
			end
	end

	def update_match
		if match.games.count >= 2
			array = match.games.pluck(:winner)
			winner = array.detect { |e| array.count(e) > 1 }
			return unless winner
			match.update_attributes(winner: winner)
			match.update_attributes(status: "Completed")
		end
	end

private	
	def set_winner
		self[:winner] = winner
	end

	def not_match_self
				return unless team_id == opponent_id
				errors.add :team , "cannot match itself"
	end

	def only_three
		return unless match.games.count >= 3
		errors.add :match , "cannot have more than 3 games"
	end

end

football/app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to @game, notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:team_id, :opponent_id, :team_score, :opponent_score, :winner, :match_id)
    end
end

football/app/helpers/games_helper.rb
module GamesHelper
end

football/app/views/games/_form.html.erb
<%= form_for(game) do |f| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= f.label :match_id %>
    <%= f.collection_select(:match_id, Match.order(:id), :id, :id) %>
  </div>

  <div class="field">
    <%= f.label :team_id %>
    <%= f.collection_select(:team_id, Team.order(:name), :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :opponent_id %>
    <%= f.collection_select(:opponent_id, Team.order(:name), :id, :name) %>
  </div>

  <div class="field">
    <%= f.label :team_score %>
    <%= f.number_field :team_score %>
  </div>

  <div class="field">
    <%= f.label :opponent_score %>
    <%= f.number_field :opponent_score %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

football/app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

football/app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

Match data will automatically update when we have a winning team.
<br>

<table>
  <thead>
    <tr>
      <th>Match</th>
      <th>Team</th>
      <th>Opponent</th>
      <th>Team score</th>
      <th>Opponent score</th>
      <th>Winner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.match.id %></td>
        <td><%= game.team.name %></td>
        <td><%= game.opponent.name %></td>
        <td><%= game.team_score %></td>
        <td><%= game.opponent_score %></td>
        <td><%= game.winner %></td>
        <td><%= link_to 'Show', game %></td>
        <td><%= link_to 'Edit', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

football/app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

football/app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Team:</strong>
  <%= @game.team.name %>
</p>

<p>
  <strong>Opponent:</strong>
  <%= @game.opponent.name %>
</p>

<p>
  <strong>Team score:</strong>
  <%= @game.team_score %>
</p>

<p>
  <strong>Opponent score:</strong>
  <%= @game.opponent_score %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>